from __future__ import annotations

from enum import Enum


class UnityProfileState(str, Enum):
    UNINITIALIZED = "UNINITIALIZED"
    CHECKING = "CHECKING"
    READY = "READY"
    EDITOR_STARTING = "EDITOR_STARTING"
    EDITOR_READY = "EDITOR_READY"
    COMPILING = "COMPILING"
    IMPORTING = "IMPORTING"
    PLAY_MODE = "PLAY_MODE"
    TESTING = "TESTING"
    BUILDING = "BUILDING"
    RUNTIME_TESTING = "RUNTIME_TESTING"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    DEGRADED = "DEGRADED"
    ERROR = "ERROR"


class CompletionBarrier(str, Enum):
    NONE = "NONE"
    EDITOR_QUIESCENT = "EDITOR_QUIESCENT"
    COMPILE_SETTLED = "COMPILE_SETTLED"
    IMPORT_AND_COMPILE_SETTLED = "IMPORT_AND_COMPILE_SETTLED"
    PLAYMODE_ENTERED = "PLAYMODE_ENTERED"
    TEST_VERDICT = "TEST_VERDICT"
    BUILD_FINISHED = "BUILD_FINISHED"
    RUNTIME_READY = "RUNTIME_READY"
